glossary = {
    'Dictionaries': 'Pythons hashtable',
    'Lists': 'Python array',
    'Tuples': 'An immutable collection of items (array)',
    'List Comprehension': 'A list that is generated by a loop: [v for v in range(10)]',
    'Get()': "Best to use if you're not certain about the value existing.",
    'Set()': 'Builds a set of unique items from a collection.',
    'Set()': 'Builds a set of unique items from a collection.',
}

# Descriptive names for key/value is great for readability
for word, meaning in glossary.items():
    print(f"{word}:\n{meaning}\n")